/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab5p2_cesarbrito;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author cesar
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_jtree = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtree = new javax.swing.JTree();
        jd_entrenador = new javax.swing.JDialog();
        js_edad_e = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        js_copas_e = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        js_contrato_e = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        agregar_entrenador = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tf_nombre_e = new javax.swing.JTextField();
        tf_apellido_e = new javax.swing.JTextField();
        tf_nacionalidad_e = new javax.swing.JTextField();
        jd_jugador = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        tf_apellido = new javax.swing.JTextField();
        tf_nacionalidad = new javax.swing.JTextField();
        js_edad = new javax.swing.JSpinner();
        js_numero = new javax.swing.JSpinner();
        js_contrato = new javax.swing.JSpinner();
        agregar_jugador = new javax.swing.JButton();
        jd_preparadorfisico = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tf_nombre_p = new javax.swing.JTextField();
        js_edad_p = new javax.swing.JSpinner();
        tf_apellido_p = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tf_nacionalidad_p = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        js_contrato_p = new javax.swing.JSpinner();
        jLabel19 = new javax.swing.JLabel();
        agregar_preparadorfisico = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        tf_especialidad_p = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        tf_titulo_p = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        ftf_id_p = new javax.swing.JFormattedTextField();
        jd_psicologo = new javax.swing.JDialog();
        tf_apellido_p1 = new javax.swing.JTextField();
        tf_titulo_p1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        tf_nacionalidad_p1 = new javax.swing.JTextField();
        ftf_id_p1 = new javax.swing.JFormattedTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        agregar_psicologo = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        tf_nombre_p1 = new javax.swing.JTextField();
        tf_especialidad_p1 = new javax.swing.JTextField();
        js_edad_p1 = new javax.swing.JSpinner();
        jLabel29 = new javax.swing.JLabel();
        popup_crud = new javax.swing.JPopupMenu();
        Eliminar = new javax.swing.JMenuItem();
        Listar = new javax.swing.JMenuItem();
        Modificar = new javax.swing.JMenuItem();
        listar_jugador = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_jugador = new javax.swing.JTable();
        listar_entrenador = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt_entrenador = new javax.swing.JTable();
        listar_preparador = new javax.swing.JDialog();
        jScrollPane4 = new javax.swing.JScrollPane();
        jt_preparador = new javax.swing.JTable();
        listar_psicologo = new javax.swing.JDialog();
        jScrollPane5 = new javax.swing.JScrollPane();
        jt_psicologo = new javax.swing.JTable();
        modificar = new javax.swing.JDialog();
        jScrollPane6 = new javax.swing.JScrollPane();
        jlist = new javax.swing.JList<>();
        jLabel27 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        jb_jugador = new javax.swing.JButton();
        jb_entrenador = new javax.swing.JButton();
        jb_psicologo = new javax.swing.JButton();
        jb_preparadorfisico = new javax.swing.JButton();
        jb_juego = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItem_jtree = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Persona");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Jugadores");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Entrenadores");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Preparadores físicos");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Psicólogos");
        treeNode1.add(treeNode2);
        jtree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jtree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtreeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtree);

        javax.swing.GroupLayout jd_jtreeLayout = new javax.swing.GroupLayout(jd_jtree.getContentPane());
        jd_jtree.getContentPane().setLayout(jd_jtreeLayout);
        jd_jtreeLayout.setHorizontalGroup(
            jd_jtreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_jtreeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
        );
        jd_jtreeLayout.setVerticalGroup(
            jd_jtreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_jtreeLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        js_edad_e.setValue(18);

        jLabel8.setText("Nombre:");

        jLabel9.setText("Apellido:");

        jLabel10.setText("Nacionalidad:");

        agregar_entrenador.setText("Agregar");
        agregar_entrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_entrenadorActionPerformed(evt);
            }
        });

        jLabel11.setText("Edad:");

        jLabel12.setText("Copas Ganadas:");

        jLabel13.setText("Años del Contrato:");

        javax.swing.GroupLayout jd_entrenadorLayout = new javax.swing.GroupLayout(jd_entrenador.getContentPane());
        jd_entrenador.getContentPane().setLayout(jd_entrenadorLayout);
        jd_entrenadorLayout.setHorizontalGroup(
            jd_entrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_entrenadorLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jd_entrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jd_entrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_entrenadorLayout.createSequentialGroup()
                        .addGroup(jd_entrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(agregar_entrenador)
                            .addComponent(tf_nombre_e)
                            .addComponent(tf_apellido_e)
                            .addComponent(tf_nacionalidad_e, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(93, Short.MAX_VALUE))
                    .addGroup(jd_entrenadorLayout.createSequentialGroup()
                        .addGroup(jd_entrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(js_contrato_e, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(js_edad_e, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(js_copas_e, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jd_entrenadorLayout.setVerticalGroup(
            jd_entrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_entrenadorLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jd_entrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_nombre_e, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_entrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_apellido_e, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_entrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_nacionalidad_e, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_entrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(js_edad_e, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_entrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(js_copas_e, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_entrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(js_contrato_e, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(agregar_entrenador)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellido:");

        jLabel4.setText("Nacionalidad:");

        jLabel5.setText("Edad:");

        jLabel6.setText("Numero:");

        jLabel7.setText("Años del Contrato:");

        js_edad.setValue(18);

        agregar_jugador.setText("Agregar");
        agregar_jugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_jugadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_jugadorLayout = new javax.swing.GroupLayout(jd_jugador.getContentPane());
        jd_jugador.getContentPane().setLayout(jd_jugadorLayout);
        jd_jugadorLayout.setHorizontalGroup(
            jd_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_jugadorLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jd_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jd_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_jugadorLayout.createSequentialGroup()
                        .addGroup(jd_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(agregar_jugador)
                            .addComponent(tf_nombre)
                            .addComponent(tf_apellido)
                            .addComponent(tf_nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(84, Short.MAX_VALUE))
                    .addGroup(jd_jugadorLayout.createSequentialGroup()
                        .addGroup(jd_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(js_contrato, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(js_edad, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(js_numero, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jd_jugadorLayout.setVerticalGroup(
            jd_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_jugadorLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jd_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(js_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(js_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(js_contrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(agregar_jugador)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        jLabel14.setText("Edad:");

        jLabel16.setText("Años del Contrato:");

        js_edad_p.setValue(18);

        jLabel17.setText("Nombre:");

        jLabel18.setText("Apellido:");

        jLabel19.setText("Nacionalidad:");

        agregar_preparadorfisico.setText("Agregar");
        agregar_preparadorfisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_preparadorfisicoActionPerformed(evt);
            }
        });

        jLabel20.setText("Especialidad:");

        jLabel21.setText("Titulo:");

        jLabel15.setText("ID:");

        ftf_id_p.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("################"))));

        javax.swing.GroupLayout jd_preparadorfisicoLayout = new javax.swing.GroupLayout(jd_preparadorfisico.getContentPane());
        jd_preparadorfisico.getContentPane().setLayout(jd_preparadorfisicoLayout);
        jd_preparadorfisicoLayout.setHorizontalGroup(
            jd_preparadorfisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_preparadorfisicoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jd_preparadorfisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_preparadorfisicoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jd_preparadorfisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jd_preparadorfisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_preparadorfisicoLayout.createSequentialGroup()
                                .addGroup(jd_preparadorfisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(tf_nombre_p)
                                    .addComponent(tf_apellido_p))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_preparadorfisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_nacionalidad_p)
                                .addComponent(tf_especialidad_p)
                                .addComponent(tf_titulo_p, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jd_preparadorfisicoLayout.createSequentialGroup()
                        .addGroup(jd_preparadorfisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jd_preparadorfisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(js_contrato_p, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftf_id_p, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(js_edad_p, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(78, 78, 78))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_preparadorfisicoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(agregar_preparadorfisico)
                .addGap(195, 195, 195))
        );
        jd_preparadorfisicoLayout.setVerticalGroup(
            jd_preparadorfisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_preparadorfisicoLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jd_preparadorfisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tf_nombre_p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_preparadorfisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tf_apellido_p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_preparadorfisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(tf_nacionalidad_p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_preparadorfisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(tf_especialidad_p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_preparadorfisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(tf_titulo_p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_preparadorfisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(ftf_id_p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_preparadorfisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(js_edad_p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_preparadorfisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(js_contrato_p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(agregar_preparadorfisico)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jLabel22.setText("Nombre:");

        jLabel23.setText("ID:");

        ftf_id_p1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("################"))));

        jLabel24.setText("Apellido:");

        jLabel25.setText("Edad:");

        jLabel26.setText("Nacionalidad:");

        agregar_psicologo.setText("Agregar");
        agregar_psicologo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_psicologoActionPerformed(evt);
            }
        });

        jLabel28.setText("Especialidad:");

        js_edad_p1.setValue(18);

        jLabel29.setText("Titulo:");

        javax.swing.GroupLayout jd_psicologoLayout = new javax.swing.GroupLayout(jd_psicologo.getContentPane());
        jd_psicologo.getContentPane().setLayout(jd_psicologoLayout);
        jd_psicologoLayout.setHorizontalGroup(
            jd_psicologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_psicologoLayout.createSequentialGroup()
                .addGroup(jd_psicologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_psicologoLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jd_psicologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel28)
                            .addComponent(jLabel26)
                            .addComponent(jLabel24)
                            .addComponent(jLabel22))
                        .addGap(18, 18, 18)
                        .addGroup(jd_psicologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tf_apellido_p1)
                            .addComponent(tf_nacionalidad_p1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_especialidad_p1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_titulo_p1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                            .addComponent(tf_nombre_p1)))
                    .addGroup(jd_psicologoLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(jd_psicologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel25))
                        .addGap(18, 18, 18)
                        .addGroup(jd_psicologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ftf_id_p1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(js_edad_p1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_psicologoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(agregar_psicologo)
                .addGap(184, 184, 184))
        );
        jd_psicologoLayout.setVerticalGroup(
            jd_psicologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_psicologoLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jd_psicologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(tf_nombre_p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_psicologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(tf_apellido_p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_psicologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(tf_nacionalidad_p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_psicologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(tf_especialidad_p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_psicologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(tf_titulo_p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_psicologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(ftf_id_p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_psicologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(js_edad_p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(agregar_psicologo)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        popup_crud.add(Eliminar);

        Listar.setText("Listar");
        Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarActionPerformed(evt);
            }
        });
        popup_crud.add(Listar);

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        popup_crud.add(Modificar);

        jt_jugador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Nacionalidad", "Edad", "Numero", "Partidos", "Copas ", "Amarillas", "Rojas", "Años"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jt_jugador);

        javax.swing.GroupLayout listar_jugadorLayout = new javax.swing.GroupLayout(listar_jugador.getContentPane());
        listar_jugador.getContentPane().setLayout(listar_jugadorLayout);
        listar_jugadorLayout.setHorizontalGroup(
            listar_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listar_jugadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
                .addContainerGap())
        );
        listar_jugadorLayout.setVerticalGroup(
            listar_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listar_jugadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jt_entrenador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Nacionalidad", "Edad", "Contrato", "Copas Gandas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jt_entrenador);

        javax.swing.GroupLayout listar_entrenadorLayout = new javax.swing.GroupLayout(listar_entrenador.getContentPane());
        listar_entrenador.getContentPane().setLayout(listar_entrenadorLayout);
        listar_entrenadorLayout.setHorizontalGroup(
            listar_entrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listar_entrenadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 821, Short.MAX_VALUE)
                .addContainerGap())
        );
        listar_entrenadorLayout.setVerticalGroup(
            listar_entrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listar_entrenadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jt_preparador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Nacionalidad", "Edad", "ID", "Contrato", "Especialidad", "Titulo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jt_preparador);

        javax.swing.GroupLayout listar_preparadorLayout = new javax.swing.GroupLayout(listar_preparador.getContentPane());
        listar_preparador.getContentPane().setLayout(listar_preparadorLayout);
        listar_preparadorLayout.setHorizontalGroup(
            listar_preparadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listar_preparadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE)
                .addContainerGap())
        );
        listar_preparadorLayout.setVerticalGroup(
            listar_preparadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listar_preparadorLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        jt_psicologo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Nacionalidad", "Edad", "ID", "Informes", "Jugadores", "Titulo", "Especialidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jt_psicologo);

        javax.swing.GroupLayout listar_psicologoLayout = new javax.swing.GroupLayout(listar_psicologo.getContentPane());
        listar_psicologo.getContentPane().setLayout(listar_psicologoLayout);
        listar_psicologoLayout.setHorizontalGroup(
            listar_psicologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listar_psicologoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 851, Short.MAX_VALUE)
                .addContainerGap())
        );
        listar_psicologoLayout.setVerticalGroup(
            listar_psicologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listar_psicologoLayout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        jlist.setModel(new DefaultListModel());
        jlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlistMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jlist);

        jLabel27.setText("Hace double click para modificar");

        javax.swing.GroupLayout modificarLayout = new javax.swing.GroupLayout(modificar.getContentPane());
        modificar.getContentPane().setLayout(modificarLayout);
        modificarLayout.setHorizontalGroup(
            modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarLayout.createSequentialGroup()
                .addGroup(modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modificarLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(modificarLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel27)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        modificarLayout.setVerticalGroup(
            modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel27)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel1.setText("AGREGAR: ");
        jToolBar1.add(jLabel1);

        jb_jugador.setText("Jugador");
        jb_jugador.setFocusable(false);
        jb_jugador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_jugador.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jb_jugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_jugadorActionPerformed(evt);
            }
        });
        jToolBar1.add(jb_jugador);

        jb_entrenador.setText("Entrenador");
        jb_entrenador.setFocusable(false);
        jb_entrenador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_entrenador.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jb_entrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_entrenadorActionPerformed(evt);
            }
        });
        jToolBar1.add(jb_entrenador);

        jb_psicologo.setText("Psicólogo");
        jb_psicologo.setFocusable(false);
        jb_psicologo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_psicologo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jb_psicologo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_psicologoActionPerformed(evt);
            }
        });
        jToolBar1.add(jb_psicologo);

        jb_preparadorfisico.setText("Preparador Físico");
        jb_preparadorfisico.setFocusable(false);
        jb_preparadorfisico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_preparadorfisico.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jb_preparadorfisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_preparadorfisicoActionPerformed(evt);
            }
        });
        jToolBar1.add(jb_preparadorfisico);

        jb_juego.setText("Juego");
        jb_juego.setFocusable(false);
        jb_juego.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_juego.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jb_juego);

        jMenu1.setText("Jtree");

        menuItem_jtree.setText("Jtree");
        menuItem_jtree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_jtreeActionPerformed(evt);
            }
        });
        jMenu1.add(menuItem_jtree);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 277, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItem_jtreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_jtreeActionPerformed
        // TODO add your handling code here:
        /*DefaultTreeModel m = (DefaultTreeModel) jtree.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
        raiz.removeAllChildren();
        for (int i = 0; i < personas.size(); i++) {
            for (int j = 0; j < raiz.getChildCount(); j++) {
                if (personas.get(i) instanceof Jugador && raiz.getChildAt(i).toString().equals("Jugadores")) {
                    DefaultMutableTreeNode p = new DefaultMutableTreeNode(personas.get(i));
                    ((DefaultMutableTreeNode) raiz.getChildAt(j)).add(p);
                }else if (personas.get(i) instanceof Entrenador && raiz.getChildAt(i).toString().equals("Entrenadores")) {
                    DefaultMutableTreeNode p = new DefaultMutableTreeNode(personas.get(i));
                    ((DefaultMutableTreeNode) raiz.getChildAt(j)).add(p);
                }else if (personas.get(i) instanceof PreparadorFisico && raiz.getChildAt(i).toString().equals("Preparadores físicos")) {
                    DefaultMutableTreeNode p = new DefaultMutableTreeNode(personas.get(i));
                    ((DefaultMutableTreeNode) raiz.getChildAt(j)).add(p);
                }else if (personas.get(i) instanceof Psicologo && raiz.getChildAt(i).toString().equals("Psicólogos")) {
                    DefaultMutableTreeNode p = new DefaultMutableTreeNode(personas.get(i));
                    ((DefaultMutableTreeNode) raiz.getChildAt(j)).add(p);
                }

            }
            m.reload();
        }*/
        jd_jtree.setModal(true);
        jd_jtree.pack();
        jd_jtree.setLocationRelativeTo(this);
        jd_jtree.setVisible(true);
    }//GEN-LAST:event_menuItem_jtreeActionPerformed

    private void agregar_jugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_jugadorActionPerformed
        // TODO add your handling code here:
        try {
            int partidosJugados = 0, copasGanadas = 0, tarjetasAmarillas = 0, tarjetasRojas = 0;
            String nombre = tf_nombre.getText();
            String apellido = tf_apellido.getText();
            String nacionalidad = tf_nacionalidad.getText();
            int edad = (Integer) js_edad.getValue();
            int numero = (Integer) js_numero.getValue();
            int contrato = (Integer) js_contrato.getValue();
            Jugador x = new Jugador(edad, numero, partidosJugados, copasGanadas, tarjetasAmarillas, tarjetasRojas, contrato, nombre, apellido, nacionalidad);
            personas.add(new Jugador(edad, numero, partidosJugados, copasGanadas, tarjetasAmarillas, tarjetasRojas, contrato, nombre, apellido, nacionalidad));
            tf_nombre.setText("");
            tf_apellido.setText("");
            tf_nacionalidad.setText("");
            js_edad.setValue(18);
            js_numero.setValue(0);
            js_contrato.setValue(0);
            DefaultTreeModel m = (DefaultTreeModel) jtree.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
            for (int j = 0; j < raiz.getChildCount(); j++) {
                if (raiz.getChildAt(j).toString().equals("Jugadores")) {
                    DefaultMutableTreeNode p = new DefaultMutableTreeNode(x);
                    ((DefaultMutableTreeNode) raiz.getChildAt(j)).add(p);
                }
            }
            m.reload();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jd_jugador, "OCURRIO UN ERROR");
        }
    }//GEN-LAST:event_agregar_jugadorActionPerformed

    private void jb_jugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_jugadorActionPerformed
        // TODO add your handling code here:
        jd_jugador.setModal(true);
        jd_jugador.pack();
        jd_jugador.setLocationRelativeTo(this);
        jd_jugador.setVisible(true);
    }//GEN-LAST:event_jb_jugadorActionPerformed

    private void agregar_entrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_entrenadorActionPerformed
        // TODO add your handling code here:
        try {
            String nombre = tf_nombre_e.getText();
            String apellido = tf_apellido_e.getText();
            String nacionalidad = tf_nacionalidad_e.getText();
            int edad = (Integer) js_edad_e.getValue();
            int copas = (Integer) js_copas_e.getValue();
            int contrato = (Integer) js_contrato_e.getValue();
            Entrenador x = new Entrenador(edad, contrato, copas, nombre, apellido, nacionalidad);
            personas.add(x);
            tf_nombre_e.setText("");
            tf_apellido_e.setText("");
            tf_nacionalidad_e.setText("");
            js_edad_e.setValue(18);
            js_copas_e.setValue(0);
            js_contrato_e.setValue(0);
            DefaultTreeModel m = (DefaultTreeModel) jtree.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
            for (int j = 0; j < raiz.getChildCount(); j++) {
                if (raiz.getChildAt(j).toString().equals("Entrenadores")) {
                    DefaultMutableTreeNode p = new DefaultMutableTreeNode(x);
                    ((DefaultMutableTreeNode) raiz.getChildAt(j)).add(p);
                }
            }
            m.reload();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jd_entrenador, "OCURRIO UN ERROR");
        }
    }//GEN-LAST:event_agregar_entrenadorActionPerformed

    private void jb_entrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_entrenadorActionPerformed
        // TODO add your handling code here:
        jd_entrenador.setModal(true);
        jd_entrenador.pack();
        jd_entrenador.setLocationRelativeTo(this);
        jd_entrenador.setVisible(true);
    }//GEN-LAST:event_jb_entrenadorActionPerformed

    private void agregar_preparadorfisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_preparadorfisicoActionPerformed
        // TODO add your handling code here:
        try {
            String nombre = tf_nombre_p.getText();
            String apellido = tf_apellido_p.getText();
            String nacionalidad = tf_nacionalidad_p.getText();
            String especialidad = tf_especialidad_p.getText();
            String titulo = tf_titulo_p.getText();
            int id = Integer.parseInt(ftf_id_p.getText());
            int edad = (Integer) js_edad_p.getValue();
            int contrato = (Integer) js_contrato_p.getValue();
            PreparadorFisico x = new PreparadorFisico(edad, id, contrato, especialidad, titulo, nombre, apellido, nacionalidad);
            personas.add(x);
            tf_nombre_p.setText("");
            tf_apellido_p.setText("");
            tf_nacionalidad_p.setText("");
            tf_especialidad_p.setText("");
            ftf_id_p.setText("");
            tf_titulo_p.setText("");
            js_edad_p.setValue(18);
            js_contrato_p.setValue(0);
            DefaultTreeModel m = (DefaultTreeModel) jtree.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
            for (int j = 0; j < raiz.getChildCount(); j++) {
                if (raiz.getChildAt(j).toString().equals("Preparadores físicos")) {
                    DefaultMutableTreeNode p = new DefaultMutableTreeNode(x);
                    ((DefaultMutableTreeNode) raiz.getChildAt(j)).add(p);
                }
            }
            m.reload();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jd_entrenador, "OCURRIO UN ERROR");
        }
    }//GEN-LAST:event_agregar_preparadorfisicoActionPerformed

    private void agregar_psicologoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_psicologoActionPerformed
        // TODO add your handling code here:
        try {
            int informes = 0, jugadoresAtendidos = 0;
            String nombre = tf_nombre_p1.getText();
            String apellido = tf_apellido_p1.getText();
            String nacionalidad = tf_nacionalidad_p1.getText();
            String especialidad = tf_especialidad_p1.getText();
            String titulo = tf_titulo_p1.getText();
            int id = Integer.parseInt(ftf_id_p1.getText());
            int edad = (Integer) js_edad_p1.getValue();
            Psicologo x = new Psicologo(edad, id, informes, jugadoresAtendidos, titulo, especialidad, nombre, apellido, nacionalidad);
            personas.add(x);
            tf_nombre_p1.setText("");
            tf_apellido_p1.setText("");
            tf_nacionalidad_p1.setText("");
            tf_especialidad_p1.setText("");
            ftf_id_p1.setText("");
            tf_titulo_p1.setText("");
            js_edad_p1.setValue(18);
            DefaultTreeModel m = (DefaultTreeModel) jtree.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
            for (int j = 0; j < raiz.getChildCount(); j++) {
                if (raiz.getChildAt(j).toString().equals("Psicólogos")) {
                    DefaultMutableTreeNode p = new DefaultMutableTreeNode(x);
                    ((DefaultMutableTreeNode) raiz.getChildAt(j)).add(p);
                }
            }
            m.reload();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jd_entrenador, "OCURRIO UN ERROR");
        }
    }//GEN-LAST:event_agregar_psicologoActionPerformed

    private void jb_psicologoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_psicologoActionPerformed
        // TODO add your handling code here:
        jd_psicologo.setModal(true);
        jd_psicologo.pack();
        jd_psicologo.setLocationRelativeTo(this);
        jd_psicologo.setVisible(true);
    }//GEN-LAST:event_jb_psicologoActionPerformed

    private void jb_preparadorfisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_preparadorfisicoActionPerformed
        // TODO add your handling code here:
        jd_preparadorfisico.setModal(true);
        jd_preparadorfisico.pack();
        jd_preparadorfisico.setLocationRelativeTo(this);
        jd_preparadorfisico.setVisible(true);
    }//GEN-LAST:event_jb_preparadorfisicoActionPerformed

    private void jtreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtreeMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            Object v1 = jtree.getSelectionPath().getLastPathComponent();
            nodo_seleccionado = (DefaultMutableTreeNode) v1;
            if (nodo_seleccionado.getUserObject() instanceof Persona) {
                persona_seleccionada = (Persona) nodo_seleccionado.getUserObject();
                popup_crud.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jtreeMouseClicked

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
        DefaultTreeModel m = (DefaultTreeModel) jtree.getModel();
        m.removeNodeFromParent(nodo_seleccionado);
        m.reload();

    }//GEN-LAST:event_EliminarActionPerformed

    private void ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarActionPerformed
        // TODO add your handling code here:        
        if (persona_seleccionada instanceof Jugador) {
            Jugador x = (Jugador) persona_seleccionada;
            int partidosJugados = x.getPartidosJugados();
            int copasGanadas = x.getCopasGanadas();
            int tarjetasAmarillas = x.getTarjetasAmarillas();
            int tarjetasRojas = x.getTarjetasRojas();
            String nombre = x.getNombre();
            String apellido = x.getApellido();
            String nacionalidad = x.getNacionalidad();
            int edad = (Integer) x.getEdad();
            int numero = (Integer) x.getNumero();
            int contrato = (Integer) x.getContrato();
            Object[] listar = {nombre, apellido, nacionalidad, edad, numero, partidosJugados, copasGanadas, tarjetasAmarillas, tarjetasRojas, contrato};
            DefaultTableModel modelo = (DefaultTableModel) jt_jugador.getModel();
            modelo.removeRow(0);
            modelo.addRow(listar);
            jt_jugador.setModel(modelo);
            listar_jugador.setModal(true);
            listar_jugador.pack();
            listar_jugador.setLocationRelativeTo(this);
            listar_jugador.setVisible(true);
        } else if (persona_seleccionada instanceof Entrenador) {
            Entrenador x = (Entrenador) persona_seleccionada;
            String nombre = x.getNombre();
            String apellido = x.getApellido();
            String nacionalidad = x.getNacionalidad();
            int edad = x.getEdad();
            int copas = x.getContrato();
            int contrato = x.getContrato();
            Object[] listar = {nombre, apellido, nacionalidad, edad, contrato, copas};
            DefaultTableModel modelo = (DefaultTableModel) jt_entrenador.getModel();
            modelo.removeRow(0);
            modelo.addRow(listar);
            jt_entrenador.setModel(modelo);
            listar_entrenador.setModal(true);
            listar_entrenador.pack();
            listar_entrenador.setLocationRelativeTo(this);
            listar_entrenador.setVisible(true);
        } else if (persona_seleccionada instanceof PreparadorFisico) {
            PreparadorFisico x = (PreparadorFisico) persona_seleccionada;
            String nombre = x.getNombre();
            String apellido = x.getApellido();
            String nacionalidad = x.getNacionalidad();
            String especialidad = x.getEspecialidad();
            String titulo = x.getTitulo();
            int id = x.getEdad();
            int edad = x.getId();
            int contrato = x.getContrato();
            Object[] listar = {nombre, apellido, nacionalidad, edad, id, contrato, especialidad, titulo};
            DefaultTableModel modelo = (DefaultTableModel) jt_preparador.getModel();
            modelo.removeRow(0);
            modelo.addRow(listar);
            jt_preparador.setModel(modelo);
            listar_preparador.setModal(true);
            listar_preparador.pack();
            listar_preparador.setLocationRelativeTo(this);
            listar_preparador.setVisible(true);
        } else if (persona_seleccionada instanceof Psicologo) {
            Psicologo x = (Psicologo) persona_seleccionada;
            int informes = x.getInformes();
            int jugadoresAtendidos = x.getJugadoresAtendidos();
            String nombre = x.getNombre();
            String apellido = x.getApellido();
            String nacionalidad = x.getNacionalidad();
            String especialidad = x.getEspecialidad();
            String titulo = x.getTitulo();
            int id = x.getId();
            int edad = x.getEdad();
            Object[] listar = {nombre, apellido, nacionalidad, edad, id, informes, jugadoresAtendidos, titulo, especialidad};
            DefaultTableModel modelo = (DefaultTableModel) jt_psicologo.getModel();
            modelo.removeRow(0);
            modelo.addRow(listar);
            jt_psicologo.setModel(modelo);
            listar_psicologo.setModal(true);
            listar_psicologo.pack();
            listar_psicologo.setLocationRelativeTo(this);
            listar_psicologo.setVisible(true);
        }
    }//GEN-LAST:event_ListarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        // TODO add your handling code here:        
        if (persona_seleccionada instanceof Jugador) {
            Jugador x = (Jugador) persona_seleccionada;
            int partidosJugados = x.getPartidosJugados();
            int copasGanadas = x.getCopasGanadas();
            int tarjetasAmarillas = x.getTarjetasAmarillas();
            int tarjetasRojas = x.getTarjetasRojas();
            String nombre = x.getNombre();
            String apellido = x.getApellido();
            String nacionalidad = x.getNacionalidad();
            int edad = (Integer) x.getEdad();
            int numero = (Integer) x.getNumero();
            int contrato = (Integer) x.getContrato();
            DefaultListModel modelo = (DefaultListModel) jlist.getModel();
            modelo.removeAllElements();
            modelo.addElement(nombre);
            modelo.addElement(apellido);
            modelo.addElement(nacionalidad);
            modelo.addElement(edad);
            modelo.addElement(numero);
            modelo.addElement(contrato);
            modelo.addElement(partidosJugados);
            modelo.addElement(copasGanadas);
            modelo.addElement(tarjetasAmarillas);
            modelo.addElement(tarjetasRojas);
            jlist.setModel(modelo);
            modificar.setModal(true);
            modificar.pack();
            modificar.setLocationRelativeTo(this);
            modificar.setVisible(true);
        } else if (persona_seleccionada instanceof Entrenador) {
            Entrenador x = (Entrenador) persona_seleccionada;
            String nombre = x.getNombre();
            String apellido = x.getApellido();
            String nacionalidad = x.getNacionalidad();
            int edad = x.getEdad();
            int copas = x.getContrato();
            int contrato = x.getContrato();
            DefaultListModel modelo = (DefaultListModel) jlist.getModel();
            modelo.removeAllElements();;
            modelo.addElement(nombre);
            modelo.addElement(apellido);
            modelo.addElement(nacionalidad);
            modelo.addElement(edad);
            modelo.addElement(copas);
            modelo.addElement(contrato);
            jlist.setModel(modelo);
            modificar.setModal(true);
            modificar.pack();
            modificar.setLocationRelativeTo(this);
            modificar.setVisible(true);
        } else if (persona_seleccionada instanceof PreparadorFisico) {
            PreparadorFisico x = (PreparadorFisico) persona_seleccionada;
            String nombre = x.getNombre();
            String apellido = x.getApellido();
            String nacionalidad = x.getNacionalidad();
            String especialidad = x.getEspecialidad();
            String titulo = x.getTitulo();
            int id = x.getEdad();
            int edad = x.getId();
            int contrato = x.getContrato();
            DefaultListModel modelo = (DefaultListModel) jlist.getModel();
            modelo.removeAllElements();;
            modelo.addElement(nombre);
            modelo.addElement(apellido);
            modelo.addElement(nacionalidad);
            modelo.addElement(especialidad);
            modelo.addElement(titulo);
            modelo.addElement(id);
            modelo.addElement(edad);
            modelo.addElement(contrato);
            jlist.setModel(modelo);
            modificar.setModal(true);
            modificar.pack();
            modificar.setLocationRelativeTo(this);
            modificar.setVisible(true);
        } else if (persona_seleccionada instanceof Psicologo) {
            Psicologo x = (Psicologo) persona_seleccionada;
            int informes = x.getInformes();
            int jugadoresAtendidos = x.getJugadoresAtendidos();
            String nombre = x.getNombre();
            String apellido = x.getApellido();
            String nacionalidad = x.getNacionalidad();
            String especialidad = x.getEspecialidad();
            String titulo = x.getTitulo();
            int id = x.getId();
            int edad = x.getEdad();
            DefaultListModel modelo = (DefaultListModel) jlist.getModel();
            modelo.removeAllElements();;
            modelo.addElement(nombre);
            modelo.addElement(apellido);
            modelo.addElement(nacionalidad);
            modelo.addElement(especialidad);
            modelo.addElement(titulo);
            modelo.addElement(id);
            modelo.addElement(edad);
            modelo.addElement(informes);
            modelo.addElement(jugadoresAtendidos);
            jlist.setModel(modelo);
            modificar.setModal(true);
            modificar.pack();
            modificar.setLocationRelativeTo(this);
            modificar.setVisible(true);
        }
    }//GEN-LAST:event_ModificarActionPerformed

    private void jlistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlistMouseClicked
        // TODO add your handling code here:
        try {
            if (jlist.getSelectedIndex() >= 0 && evt.getClickCount() == 2) {
                DefaultListModel modelo = (DefaultListModel) jlist.getModel();
                int po = jlist.getSelectedIndex();
                if (persona_seleccionada instanceof Jugador) {
                    Jugador x = (Jugador) persona_seleccionada;
                    if (po == 0) {
                        String nombre = JOptionPane.showInputDialog("Ingrese el nombre: ");
                        x.setNombre(nombre);
                        modelo.set(po, nombre);
                    } else if (po == 1) {
                        String nombre = JOptionPane.showInputDialog("Ingrese el apellido: ");
                        x.setApellido(nombre);
                        modelo.set(po, nombre);
                    } else if (po == 2) {
                        String nombre = JOptionPane.showInputDialog("Ingrese la nacionalidad: ");
                        x.setNacionalidad(nombre);
                        modelo.set(po, nombre);
                    } else if (po == 3) {
                        int num = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la edad: "));
                        x.setEdad(num);
                        modelo.set(po, num);
                    } else if (po == 4) {
                        int num = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el numero: "));
                        x.setNumero(num);
                        modelo.set(po, num);
                    } else if (po == 5) {
                        int num = Integer.parseInt(JOptionPane.showInputDialog("Ingrese los años del contrato: "));
                        x.setContrato(num);
                        modelo.set(po, num);
                    } else if (po == 6) {
                        int partidosJugados = Integer.parseInt(JOptionPane.showInputDialog("Ingrese partidos jugados: "));
                        x.setPartidosJugados(partidosJugados);
                        modelo.set(po, partidosJugados);
                    } else if (po == 7) {
                        int num = Integer.parseInt(JOptionPane.showInputDialog("Ingrese las copas ganadas: "));
                        x.setCopasGanadas(num);
                        modelo.set(po, num);
                    } else if (po == 8) {
                        int num = Integer.parseInt(JOptionPane.showInputDialog("Ingrese las tarjetas amarillas: "));
                        x.setTarjetasAmarillas(num);
                        modelo.set(po, num);
                    } else if (po == 9) {
                        int num = Integer.parseInt(JOptionPane.showInputDialog("Ingrese las tarjetas rojas: "));
                        x.setTarjetasRojas(num);
                        modelo.set(po, num);
                    }
                    DefaultTreeModel m = (DefaultTreeModel) jtree.getModel();
                    nodo_seleccionado.setUserObject(x);
                    m.reload();
                } else if (persona_seleccionada instanceof Entrenador) {
                    Entrenador x = (Entrenador) persona_seleccionada;
                    String nombre = x.getNombre();
                    String apellido = x.getApellido();
                    String nacionalidad = x.getNacionalidad();
                    int edad = x.getEdad();
                    int copas = x.getContrato();
                    int contrato = x.getContrato();
                    DefaultTreeModel m = (DefaultTreeModel) jtree.getModel();
                    nodo_seleccionado.setUserObject(x);
                    m.reload();
                } else if (persona_seleccionada instanceof PreparadorFisico) {
                    PreparadorFisico x = (PreparadorFisico) persona_seleccionada;
                    String nombre = x.getNombre();
                    String apellido = x.getApellido();
                    String nacionalidad = x.getNacionalidad();
                    String especialidad = x.getEspecialidad();
                    String titulo = x.getTitulo();
                    int id = x.getEdad();
                    int edad = x.getId();
                    int contrato = x.getContrato();
                } else if (persona_seleccionada instanceof Psicologo) {
                    Psicologo x = (Psicologo) persona_seleccionada;
                    int informes = x.getInformes();
                    int jugadoresAtendidos = x.getJugadoresAtendidos();
                    String nombre = x.getNombre();
                    String apellido = x.getApellido();
                    String nacionalidad = x.getNacionalidad();
                    String especialidad = x.getEspecialidad();
                    String titulo = x.getTitulo();
                    int id = x.getId();
                    int edad = x.getEdad();
                }
                jlist.setModel(modelo);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jd_entrenador, "OCURRIO UN ERROR");
        }
    }//GEN-LAST:event_jlistMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JMenuItem Listar;
    private javax.swing.JMenuItem Modificar;
    private javax.swing.JButton agregar_entrenador;
    private javax.swing.JButton agregar_jugador;
    private javax.swing.JButton agregar_preparadorfisico;
    private javax.swing.JButton agregar_psicologo;
    private javax.swing.JFormattedTextField ftf_id_p;
    private javax.swing.JFormattedTextField ftf_id_p1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton jb_entrenador;
    private javax.swing.JButton jb_juego;
    private javax.swing.JButton jb_jugador;
    private javax.swing.JButton jb_preparadorfisico;
    private javax.swing.JButton jb_psicologo;
    private javax.swing.JDialog jd_entrenador;
    private javax.swing.JDialog jd_jtree;
    private javax.swing.JDialog jd_jugador;
    private javax.swing.JDialog jd_preparadorfisico;
    private javax.swing.JDialog jd_psicologo;
    private javax.swing.JList<String> jlist;
    private javax.swing.JSpinner js_contrato;
    private javax.swing.JSpinner js_contrato_e;
    private javax.swing.JSpinner js_contrato_p;
    private javax.swing.JSpinner js_copas_e;
    private javax.swing.JSpinner js_edad;
    private javax.swing.JSpinner js_edad_e;
    private javax.swing.JSpinner js_edad_p;
    private javax.swing.JSpinner js_edad_p1;
    private javax.swing.JSpinner js_numero;
    private javax.swing.JTable jt_entrenador;
    private javax.swing.JTable jt_jugador;
    private javax.swing.JTable jt_preparador;
    private javax.swing.JTable jt_psicologo;
    private javax.swing.JTree jtree;
    private javax.swing.JDialog listar_entrenador;
    private javax.swing.JDialog listar_jugador;
    private javax.swing.JDialog listar_preparador;
    private javax.swing.JDialog listar_psicologo;
    private javax.swing.JMenuItem menuItem_jtree;
    private javax.swing.JDialog modificar;
    private javax.swing.JPopupMenu popup_crud;
    private javax.swing.JTextField tf_apellido;
    private javax.swing.JTextField tf_apellido_e;
    private javax.swing.JTextField tf_apellido_p;
    private javax.swing.JTextField tf_apellido_p1;
    private javax.swing.JTextField tf_especialidad_p;
    private javax.swing.JTextField tf_especialidad_p1;
    private javax.swing.JTextField tf_nacionalidad;
    private javax.swing.JTextField tf_nacionalidad_e;
    private javax.swing.JTextField tf_nacionalidad_p;
    private javax.swing.JTextField tf_nacionalidad_p1;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_nombre_e;
    private javax.swing.JTextField tf_nombre_p;
    private javax.swing.JTextField tf_nombre_p1;
    private javax.swing.JTextField tf_titulo_p;
    private javax.swing.JTextField tf_titulo_p1;
    // End of variables declaration//GEN-END:variables
    ArrayList<Persona> personas = new ArrayList();
    DefaultMutableTreeNode nodo_seleccionado;
    Persona persona_seleccionada;
    int indexpersona;
}
